<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyTitle>D8 Flash Tester</AssemblyTitle>
    <Product>D8 Flash Tester</Product>
    <Company>Digital8Dreamz</Company>
    <Version>2.7.0</Version>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="app.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
